site_name: versions
site_author: nekitdev
site_description: Parsing, inspecting and specifying versions.

repo_name: nekitdev/versions
repo_url: https://github.com/nekitdev/versions

remote_branch: github-pages

nav:
  - Index: "index.md"

  - Reference:
    - Functions: "reference/functions.md"
    - Version: "reference/version.md"
    - Versioned: "reference/versioned.md"
    - Meta: "reference/meta.md"
    - Segments: "reference/segments.md"
    - Specification: "reference/specification.md"
    - Version Sets: "reference/version_sets.md"
    - Specifiers: "reference/specifiers.md"
    - Converters: "reference/converters.md"
    - Operators: "reference/operators.md"
    - Types: "reference/types.md"
    - Errors: "reference/errors.md"

  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - versions

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true

          paths: [versions]

          import:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
